name: workflow.yml
on: push
#  schedule:
#    - cron: "0 */6 * * *"

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install .venv
        run: pip install .

      - name: Create .env
        run: |
          touch .env
          echo "TOKEN=${{ secrets.TOKEN }}" >> .env
          echo "CLAN_TAG=${{ vars.CLAN_TAG }}" >> .env 

      - name: Run
        run: python war_stats.py